name: FakeFill
version: ${project.version}
main: me.awesomepandapig.fakefill.FakeFill
api-version: 1.16
description: This plugin lets you change the appearance of blocks.
author: awesomepandapig

commands:
  fakefill:
  help:
  fset:
    description: Changes the appearance of a single block
    permission: fakefill.use
  ffill:
    description: Changes the appearance of all blocks within a selection
    permission: fakefill.use
  freplace:
    description: Changes the appearance of certain blocks within a selection
    permission: fakefill.use